sl_index:
    resource: "@SLIndexBundle/Resources/config/routing.yml"
    prefix:   /

sl_users:
    resource: "@SLUsersBundle/Resources/config/routing.yml"
    prefix:   /users

sl_etablissement:
    resource: "@SLEtablissementBundle/Resources/config/routing.yml"
    prefix:   /etablissement

login:
    pattern:   /login
    defaults:  { _controller: SLUsersBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

